version: '3'
services:
  suff.de-v-backend:
    build: .devcontainer/
    ports: 8000:8000
    volumes:
      - ./suff.de-v-backend:/workspace
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: